/**
 * Exact section map from the My Profile mockups (per role).
 * Label fields are i18n keys under `panel.profile.*`.
 *
 * 1 admin       — name+email, full password, IBAN
 * 2 affiliate   — name+email+phone, simple password, IBAN
 * 3 transporter — split cards, avatar upload, personal info, IBAN
 * 4 factory     — phone + warehouses, simple password, IBAN
 * 5 supplier    — phone + warehouses, full password, IBAN
 * 6 customer    — buyer account: avatar, address fields, password, IBAN, billing/shipping
 */
export const PANEL_PROFILE_ROLE_CONFIG = {
  customer: {
    layout: 'buyer',
    showPageHeader: false,
    showAvatarActions: false,
    showAccountPhone: true,
    showWarehouses: false,
    passwordMode: 'full',
    showIban: true,
    showAddressCards: true,
    subtitleKey: 'panel.profile.subtitleBuyer',
    accountTitleKey: 'panel.profile.accountSetting',
    nameLabelKey: 'panel.profile.name',
    passwordTitleKey: 'panel.profile.changePassword',
    newPasswordLabelKey: 'panel.profile.newPassword',
    confirmPasswordLabelKey: 'panel.profile.confirmNewPassword',
    updateProfileLabelKey: 'panel.profile.saveChanges',
    changePasswordLabelKey: 'panel.profile.changePasswordUpper',
    profileActionsAlign: 'start',
    passwordActionsAlign: 'start',
    ibanPhoneLabelKey: 'panel.profile.ibanPhoneEurope',
    ibanPhonePlaceholderKey: 'panel.profile.ibanPhonePlaceholder',
  },
  admin: {
    layout: 'combined',
    showAvatarActions: false,
    showAccountPhone: false,
    showWarehouses: false,
    passwordMode: 'full',
    showIban: true,
    subtitleKey: 'panel.profile.subtitle',
    accountTitleKey: 'panel.profile.accountInformation',
    nameLabelKey: 'panel.profile.name',
    passwordTitleKey: 'panel.profile.changePassword',
    newPasswordLabelKey: 'panel.profile.newPassword',
    confirmPasswordLabelKey: 'panel.profile.confirmNewPassword',
    updateProfileLabelKey: 'panel.profile.updateProfile',
    changePasswordLabelKey: 'panel.profile.changePassword',
    profileActionsAlign: 'end',
    passwordActionsAlign: 'end',
    ibanPhoneLabelKey: 'panel.profile.ibanPhoneEupago',
    ibanPhonePlaceholderKey: 'panel.profile.ibanPhonePlaceholder',
  },
  affiliate: {
    layout: 'combined',
    showAvatarActions: false,
    showAccountPhone: true,
    showWarehouses: false,
    passwordMode: 'simple',
    showIban: true,
    subtitleKey: 'panel.profile.subtitle',
    accountTitleKey: 'panel.profile.accountInformation',
    nameLabelKey: 'panel.profile.name',
    passwordTitleKey: 'panel.profile.changePassword',
    newPasswordLabelKey: 'panel.profile.newPassword',
    confirmPasswordLabelKey: 'panel.profile.confirmNewPassword',
    updateProfileLabelKey: 'panel.profile.updateProfile',
    changePasswordLabelKey: 'panel.profile.changePassword',
    profileActionsAlign: 'end',
    passwordActionsAlign: 'end',
    ibanPhoneLabelKey: 'panel.profile.ibanPhoneEpagar',
    ibanPhonePlaceholderKey: 'panel.profile.ibanPhonePlaceholder',
  },
  transporter: {
    layout: 'split',
    showAvatarActions: true,
    showAccountPhone: true,
    showWarehouses: false,
    passwordMode: 'simple',
    showIban: true,
    subtitleKey: 'panel.profile.subtitleTransporter',
    accountTitleKey: 'panel.profile.personalInformation',
    nameLabelKey: 'panel.profile.fullName',
    passwordTitleKey: 'panel.profile.updatePassword',
    newPasswordLabelKey: 'panel.profile.password',
    confirmPasswordLabelKey: 'panel.profile.confirmPassword',
    updateProfileLabelKey: 'panel.profile.saveChanges',
    changePasswordLabelKey: 'panel.profile.saveChanges',
    profileActionsAlign: 'end',
    passwordActionsAlign: 'end',
    ibanPhoneLabelKey: 'panel.profile.ibanPhoneBackup',
    ibanPhonePlaceholderKey: 'panel.profile.ibanPhonePlaceholder',
  },
  factory: {
    layout: 'combined',
    showAvatarActions: false,
    showAccountPhone: true,
    showWarehouses: true,
    passwordMode: 'simple',
    showIban: true,
    subtitleKey: 'panel.profile.subtitle',
    accountTitleKey: 'panel.profile.accountInformation',
    nameLabelKey: 'panel.profile.name',
    passwordTitleKey: 'panel.profile.changePassword',
    newPasswordLabelKey: 'panel.profile.newPassword',
    confirmPasswordLabelKey: 'panel.profile.confirmNewPassword',
    updateProfileLabelKey: 'panel.profile.updateProfile',
    changePasswordLabelKey: 'panel.profile.changePassword',
    profileActionsAlign: 'end',
    passwordActionsAlign: 'end',
    ibanPhoneLabelKey: 'panel.profile.ibanPhoneBackup',
    ibanPhonePlaceholderKey: 'panel.profile.ibanPhonePlaceholderLong',
  },
  supplier: {
    layout: 'combined',
    showAvatarActions: false,
    showAccountPhone: true,
    showWarehouses: true,
    passwordMode: 'full',
    showIban: true,
    subtitleKey: 'panel.profile.subtitle',
    accountTitleKey: 'panel.profile.accountInformation',
    nameLabelKey: 'panel.profile.name',
    passwordTitleKey: 'panel.profile.changePassword',
    newPasswordLabelKey: 'panel.profile.newPassword',
    confirmPasswordLabelKey: 'panel.profile.confirmNewPassword',
    updateProfileLabelKey: 'panel.profile.updateProfile',
    changePasswordLabelKey: 'panel.profile.changePassword',
    profileActionsAlign: 'end',
    passwordActionsAlign: 'end',
    ibanPhoneLabelKey: 'panel.profile.ibanPhoneEupago',
    ibanPhonePlaceholderKey: 'panel.profile.ibanPhonePlaceholder',
  },
}

export function resolveProfileConfig(role, overrides = {}) {
  const base =
    PANEL_PROFILE_ROLE_CONFIG[role] || PANEL_PROFILE_ROLE_CONFIG.supplier
  const cleaned = Object.fromEntries(
    Object.entries(overrides).filter(([, value]) => value !== undefined),
  )
  return { ...base, ...cleaned }
}
